### ISSUE TITLE
gradle exception

### ISSUE THREAD

**Issue by mathume** [commercehub-oss/gradle-cucumber-jvm-plugin#31]
gradle 2.10
gradle --stacktrace myCucumberSuite
>>
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myCucumberSuite'.
...
Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/logging/progress/ProgressLoggerFactory
        at com.commercehub.gradle.cucumber.CucumberTask.runTests(CucumberTask.groovy:35)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
