### ISSUE TITLE
:cucumberTest - Could not start process: Exception

### ISSUE THREAD

**Issue by sharmasourabh** [commercehub-oss/gradle-cucumber-jvm-plugin#37]
Using 0.7 version of plugin. On windows 7, I got the following error:

Executing task ':cucumberTest' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Could not start process:
java.io.IOException: Cannot run program "c:\jdk8\jre\bin\java": CreateProcess error=206, The filename or extension is too long
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:931)
        at org.zeroturnaround.exec.ProcessExecutor.startInternal(ProcessExecutor.java:910)
        at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:860)
        at org.zeroturnaround.exec.ProcessExecutor$execute$3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at com.commercehub.gradle.cucumber.JavaProcessLauncher.execute(JavaProcessLauncher.groovy:64)
        at com.commercehub.gradle.cucumber.JavaProcessLauncher$execute$3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at com.commercehub.gradle.cucumber.CucumberRunner$_run_closure2_closure5.doCall(CucumberRunner.groovy:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at groovyx.gpars.pa.GParsPoolUtilHelper$_eachParallelPA_closure8.doCall(GParsPoolUtilHelper.groovy:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:53)
        at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:105)
        at com.sun.proxy.$Proxy75.op(Unknown Source)
        at groovyx.gpars.extra166y.AbstractParallelAnyArray$OUPap.leafApply(AbstractParallelAnyArray.java:640)
        at groovyx.gpars.extra166y.PAS$FJOApply.atLeaf(PAS.java:147)
        at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:108)
        at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
        at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
        at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
        at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
        at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
        at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 47 more
:cucumberTest FAILED
:cucumberTest (Thread[main,5,main]) completed. Took 0.4 secs.

Could you please help to resolve this issue?

**Comment by JayStGelais** [comment]
@sharmasourabh 

My guess is that you are running into a limit on the length of a command line in windows. The classpath for your tests are being written to this command line and is likely the cause. I don't have a clear idea for a fix. You might be able to work around this by trimming your classpath or reducing the average length of the paths to jars by storing them elsewhere.

If you come up with a novel way to reliably shorten the classpath portion of the command line programmatically, we would be open to adding it via a pull request.

**Comment by RajAsapu** [comment]
@sharmasourabh : Add these flags in your build.gradle file 
   reports.junitXml.enabled = false
    reports.html.enabled = false
and give a try . They are used to turn off the report generation as the longer names are not supported.

**Comment by sharmasourabh** [comment]
Thanks @RajAsapu. I tried it, still facing same issue.

**Comment by RajAsapu** [comment]
@sharmasourabh do you have those flags in test task 
eg:
test {
    reports.junitXml.enabled = false
    reports.html.enabled = false
}

**Comment by sharmasourabh** [comment]
I placed these flags in test {} only. Do I need to place in somewhere else?

**Comment by RajAsapu** [comment]
@sharmasourabh : No it should be in test. You did it right . What is your task to run the cucumber tests ? Is it cucumberTests . You should place the above tags in which ever task you are running either test or any custom task. that should work, give it a try.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
